export const TOGGLE_SONG_LIST = 'TOGGLE_SONG_LIST'

export const TOGGLE_CONFIG_PANEL = 'TOGGLE_CONFIG_PANEL'

export const UPDATE_SONG_INFO = 'UPDATE_SONG_INFO'

export const UPDATE_PLAYER_STATE = 'UPDATE_PLAYER_STATE'

export const SET_AUDIO_ELEMENT = 'SET_AUDIO_ELEMENT'

export const NEXT_SONG = 'NEXT_SONG'

export const PREV_SONG = 'PREV_SONG'

export const UPDATE_CURRENT_TIME = 'UPDATE_CURRENT_TIME'

export const UPDATE_PLAY_MODE = 'UPDATE_PLAY_MODE'

export const UPDATE_REPEAT_MODE = 'UPDATE_REPEAT_MODE'

export const REPEAT_SONG = 'REPEAT_SONG'

export const RANDOM_SONG = 'RANDOM_SONG'